/*EXERCISE 6-1
If set A = {L M N O P} and set B = {P Q R S T}, what sets are generated by the following
operations?
• A union B
• A union all B
• A intersect B
• A except B*/


/*EXERCISE 6-2
Write a compound query that finds the first and last names of all actors and customers
whose last name starts with L.*/


/*EXERCISE 6-3
Sort the results from Exercise 6-2 by the last_name column.*/

